/* ---------------------------------------------------------------------------
 * Settings you edit by hand. Everything else is generated by build_study.py.
 * ------------------------------------------------------------------------- */

window.STUDY_CONFIG = {
  /* Paste the /exec URL of your deployed Apps Script web app here.
     See apps_script/Code.gs and the README for the five-minute setup.
     Left empty, the study still runs end to end and offers participants a
     download of their answers instead. */
  endpoint: "https://script.google.com/macros/s/AKfycbxQyUEx1XfU4YrPQd0P7VDOwbb-NCftMNaVbMZ03ZaKtKt4EhGADg9w5nylZUf-DgHz/exec",

  /* Shown in the header and the browser tab. */
  name: "Mix-and-Match: User Study",

  /* Optional. An address participants can write to with questions. Leave empty
     to omit the line entirely rather than publish an address to scrapers. */
  contact: "",

  /* Optional. A link to the project or paper, shown on the thank-you screen. */
  projectUrl: "",

  manifestUrl: "data/manifest.json",

  /* Grid width of a picture taller than it is wide, as a fraction of its cell. Only
     Tiled Diffusion's vertical stacks are, and at full width they dwarf the rest. */
  tallScale: 0.5,

  /* How long the chosen picture stays highlighted before the next question. */
  advanceDelayMs: 280
};
